contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'about/',
        views.display_about,
        name='about'),
    path(
        'contact_us',
        views.display_contact,
        name='contact_details'),
]

littlewhitedress/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('customers/', include('django.contrib.auth.urls')),
    path('customers/', include('customer.urls')),
    path('community/', include('recommendations.urls')),
    path('contact/', include('contact.urls')),
    path('appointment/', include('appointment.urls')),
]

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.display_homepage,
        name='index'),
    path(
        'products/',
        views.ProductList.as_view(),
        name='products'),
    path(
        'category/<str:selected_cat>/',
        views.category_products,
        name='category'),
    path(
        'product/<int:pk>',
        views.ProductDetails.as_view(),
        name='product_details'),
    path(
        'like/<int:pk>',
        views.customer_favourites,
        name='customer_fav'),
]

product/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User


class Category(models.Model):
    """
    Category model links to the Product Model
    Each Product belongs to a Category
    """
    category_image = CloudinaryField('image', default='placeholderCategory')
    category_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.category_name


class Product(models.Model):
    """
    Product models holds all information relating to products
    """
    main_image = CloudinaryField('image', default='placeholderProduct')
    item_name = models.CharField(max_length=50, unique=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    description = models.TextField(
        default='Contact us to find out more about this gown',
        blank=True,
        max_length=2000)
    colours = models.TextField(default='Ivory', blank=True, max_length=500)
    sizes_avail = models.TextField(
        default='8 - 26', blank=True, max_length=500)
    likes = models.ManyToManyField(
        User, related_name='fav_products', blank=True)

    def __str__(self):
        return self.item_name

product/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Category, Product
from recommendations.models import Recommendation
from django.http import HttpResponseRedirect
from django.urls import reverse


def customer_favourites(request, pk):
    """
    Adds liked products to customer record
    """
    product = get_object_or_404(Product, id=request.POST.get('product_id'))
    liked = False
    if product.likes.filter(id=request.user.id).exists():
        product.likes.remove(request.user)
        liked = False
    else:
        product.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('product_details', args=[str(pk)]))


class ProductDetails(generic.DetailView):
    """
    Displays individual product details
    """
    model = Product
    template_name = 'product_details.html'

    # Code adapted from Codemy 'Add Blog Posts to Django' tutorial:
    # https://bit.ly/3s2sUq4
    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetails, self).get_context_data(*args, **kwargs)
        data = get_object_or_404(Product, id=self.kwargs['pk'])
        liked = False
        if data.likes.filter(id=self.request.user.id).exists():
            liked = True
        context['liked'] = liked
        return context


def category_products(request, selected_cat):
    """
    Displays all products within the selected category
    """
    category_products = Product.objects.filter(
        category__category_name=selected_cat)
    return render(
        request,
        'category_products.html',
        {'selected_cat': selected_cat, 'category_products': category_products})


class ProductList(generic.ListView):
    """
    Displays all products when 'all styles' is selected
    """
    model = Product
    template_name = 'all_products.html'


def display_homepage(request):
    """
    Displays Homepage
    Passes in all objects from Category model
    Passes Recommendation model objects to be displayed
    """
    category_list = Category.objects.all()
    recommendation_list = Recommendation.objects.all()

    context = {
        'category_list': category_list,
        'recommendation_list': recommendation_list,
    }
    return render(request, 'index.html', context)

product/templates/all_products.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <h1 class="text-center"><em>All Styles</em></h1>
    <div class="container-fluid">
        <div class="row">
            {% for product in product_list %}
                <div class="card-body products-container col-sm-6 col-lg-4 col-xl-3">
                    <a href="{% url 'product_details' product.pk %}" class="product-link">
                        <div class="image-container product-image">
                            <img src=" {{ product.main_image.url }}" alt="product image">
                        </div>
                        <div class="text-center">
                            <h3 class="link-no-decor">{{ product.item_name }}</h3>
                            <p class="link-no-decor">{{ product.category }}</p>
                            <p class="link-no-decor">£{{ product.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>  
    </div>
</div>

{% endblock %}

product/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.gstatic.com">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous">
    </script>
    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Little White Dress</title>
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}"><span class="brand">Little White Dress</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            My Account
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.customer.id %}
                                    <li><a class="dropdown-item" href="{% url 'profile' user.customer.id %}">Profile</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'create_profile' %}">Create Profile</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'settings' %}">Settings</a></li>
                            </ul>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container-fluid text-center mt-3 py-3">
            <a class="link-no-decor social-media-links" href="http://pinterest.com" target="_blank" rel="noopener" aria-label="visit our pinterest page (opens in new tab)"><i class="fa-brands fa-pinterest"></i></a>
            <a class="link-no-decor social-media-links" href="http://instagram.com" target="_blank" rel="noopener" aria-label="visit our instagram page (opens in new tab)"><i class="fa-brands fa-instagram"></i></a>
            <a class="link-no-decor social-media-links" href="http://facebook.com" target="_blank" rel="noopener" aria-label="visit our facebook page (opens in new tab)"><i class="fa-brands fa-facebook"></i></a>
            <a class="link-no-decor social-media-links" href="http://tiktok.com" target="_blank" rel="noopener" aria-label="visit our tiktok page (opens in new tab)"><i class="fa-brands fa-tiktok"></i></a>
        </div>
        <div class="container-fluid text-center">
            <p class="mb-0">This is a fictional site created for educational purposes</p>
            <p class="mb-0 pb-3">Copyright <i class="fa-regular fa-copyright"></i> KSL Designs</p>
        </div>
    </footer>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b59d6ce89e.js" crossorigin="anonymous"></script>
</body>

</html>

product/templates/category_products.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid body-content">
    {% if category_products %}
        <h1 class="text-center"><em>{{ selected_cat }}</em></h1>
        
        <div class="container-fluid">
            <div class="row">
                {% for product in category_products %}
                    <div class="card-body products-container col-sm-6 col-lg-4">
                        <a href="{% url 'product_details' product.pk %}" class="product-link">
                            <div class="image-container product-image">
                                <img src=" {{ product.main_image.url }}" alt="product image">
                            </div>
                            <div class="text-center">
                                <h3>{{ product.item_name }}</h3>
                                <p>{{ product.category }}</p>
                                <p>£{{ product.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% else %}

        <h3>Sorry this page does not exist</h3>
        <button>Go Back</button>

    {% endif %}
</div>

{% endblock %}

product/templates/index.html
{% extends 'base.html' %}

{% block content %}

<!-- Hero image -->
<div class="container-fluid hero-container">
    <div class="text-center big-btn">
        {% if user.is_authenticated %}
            {% if user.customer.id %}
                <a href="{% url 'book' user.customer.id %}" class="link-no-decor">
                    <p class="mb-0 mobile-btn py-1"><em>Book an appointment</em></p>
                </a>
            {% else %}
                <a href="{% url 'create_profile' %}" class="link-no-decor">
                    <p class="mb-0 mobile-btn py-1"><em>Book an appointment</em></p>
                </a>
            {% endif %}
        {% else %}
            <a href="{% url 'login' %}" class="link-no-decor">
                <p class="mb-0 mobile-btn py-1"><em>Book an appointment</em></p>
            </a>
        {% endif %}
    </div>
    <div>
        <div class="carousel-inner">
            <div>
                <img src="https://res.cloudinary.com/ksjl86/image/upload/v1691570875/hero_3_em3ezd.webp"
                    class="d-block w-100 hero-image" alt="Image of a woman wearing a wedding dress and browsing other wedding dresses that are hanging on hangers">
                <div class="carousel-overlay text-center">
                    <h2 id="hero-text"><em>Find your perfect gown</em></h2>
                    {% if user.is_authenticated %}
                        {% if user.customer.id %}
                        <a href="{% url 'book' user.customer.id %}" class="link-no-decor">
                            <p class="hero-btn homepage-btn"><em>Book an appointment</em></p>
                        </a>
                        {% else %}
                        <a href="{% url 'create_profile' %}" class="link-no-decor">
                            <p class="hero-btn homepage-btn"><em>Book an appointment</em></p>
                        </a>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'login' %}" class="link-no-decor">
                            <p class="hero-btn homepage-btn"><em>Book an appointment</em></p>
                        </a>
                    {% endif %}
                </div>
            </div>
    </div>

    <!-- Collections section -->
    <div class="text-center mt-3 pt-4 pb-1">
        <h2><em>Our Collections</em></h2>
        <a href="{% url 'products' %}" class="link-no-decor">
            <p class="homepage-btn">Shop all styles</p>
        </a>
    </div>

    <div class="container-fluid category-section">
        <div class="row">

            <!-- Collections Category Row -->
            <div class="col-12 scroll-animation">
                <div class="row category row-cols-sm-3 row-cols-md-4 collection-container">
                    {% for category in category_list %}
                    <div class="card-body">
                        <a href="{% url 'category' category.category_name %}" class="category-link">
                            <div>
                                <img src=" {{ category.category_image.url }}" alt="category image">
                            </div>
                            <h3 class="card-title">{{ category.category_name }}</h3>
                        </a>
                    </div>
                    {% if forloop.counter|divisibleby:6 %}
                </div>
                <div class="row category-row">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
    <!-- Come and see us section -->
    <div class="container-fluid section-title appt-section align-items-center scroll-animation">
        <h2 class="pt-3"><em>Come and See Us</em></h2>
        <p class="lead">Trying on dresses is a right of passage for any bride. We'll make your experience as special as it should be.</p>
        <p class="lead">Bring up to 5 guests, enjoy a glass of fizz, and let's see if we can find your <em>'one' </em>!</p>
        {% if user.is_authenticated %}
            {% if user.customer.id %}
                <a href="{% url 'book' user.customer.id %}" class="link-no-decor">
                    <p class="appt-btn homepage-btn">Book an Appointment</p>
                </a>
            {% else %}
                <a href="{% url 'create_profile' %}" class="link-no-decor">
                    <p class="appt-btn homepage-btn"><em>Book an appointment</em></p>
                </a>
            {% endif %}
        {% else %}
            <a href="{% url 'login' %}" class="link-no-decor">
                <p class="appt-btn homepage-btn">Book an Appointment</p>
            </a>
        {% endif %}     
    </div>

    <!-- Community section -->
    <div class="container-fluid section-title mt-3">
        {% if user.is_authenticated %}
            <a class="link-no-decor link-hover" href="{% url 'community' %}"><h2><em>Join our community of Brides</em></h2></a>
        {% else %}
            <a class="link-no-decor link-hover" href="{% url 'login' %}"><h2><em>Join our community of Brides</em></h2></a>
        {% endif %}
        <p class="lead"><a class="link-no-decor link-hover" href="{% url 'register' %}">Register</a> or <a class="link-no-decor link-hover" href="{% url 'login' %}">Login</a> now to read more and contribute your recommendations to other brides</p>

        <!-- Sample of Recommendations -->
        <div class="col-12 px-2">
            <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 justify-content-center">
                {% for item in recommendation_list|slice:"0:4" %}
                    <div class="card-body recommendation-cards m-4 scroll-animation">
                        <div class="p-4">
                            <h3 class="link-no-decor text-uppercase">{{ item.type_of_recommendation }}</h3>
                            <h3 class="link-no-decor">{{ item.title }}</h3>
                            <p class="link-no-decor"><em>Location: {{ item.location }}</em></p>
                            <h4><a class="link-no-decor link-hover" href="http://{{ item.web_link }}" target="_blank" rel="noopener"><i class="fa-light fa-globe-pointer"></i> Visit Website</a></h4>
                            <p class="link-no-decor lead">{{ item.summary }}</p>
                            <p class="link-no-decor"><em>Posted on: {{ item.date_posted }}</em></p>
                            <p class="link-no-decor"><em>Posted by: {{ item.posted_by }}</em></p>
                        </div>
                    </div> 
                {% endfor %}   
            </div>
        </div>
        <div class="mt-4 pt-2">
            {% if user.is_authenticated %}
                <a class="link-no-decor link-hover" href="{% url 'community' %}"><h3>Read more recommendations now, or add your own!</h3></a>
            {% else %}
                <a class="link-no-decor link-hover" href="{% url 'login' %}"><h3>Read more recommendations now, or add your own!</h3></a>
            {% endif %}
        </div>
    </div>

    <!-- Page Divider -->
    <div class="divider"><div class="divider-inner"></div><span><i class="fa-thin fa-circle-heart"></i></span></div>
    
    <!-- Testimonials section -->
    <div class="outer-section scroll-animation">
        <div class="container-fluid section-title brides-section">
            <h2><em>Meet Our Brides</em></h2>
            <div class="row brides-row-1">
                <div class="brides-text-first col-12 col-sm-6">
                    <h3>Kate & James</h3>
                    <p><em>"As a plus size bride I was really nervous about trying on dresses, but Sam was so incredibly welcoming and made me feel just as special and deserving as any other bride"</em></p>
                </div>
                <div class="brides-img col-12 col-sm-6 d-flex justify-content-center justify-content-sm-start">
                    <img class="rounded-circle" src="https://res.cloudinary.com/ksjl86/image/upload/v1691575581/katejames_ycuqt7_sugd3w.webp" alt="Image of bride and groom Kate & James on their wedding day">
                </div>
            </div>
            <div class="row pt-2">
                <div class="brides-text-second col-12 col-sm-6">
                    <h3>Jane & Mike</h3>
                    <p><em>"If it wasn't for Samantha at Little White Dress I would never have even tried on the style that I ended up having. I'm so grateful to her for all her patience and honest advice!"</em></p>
                </div>
                <div class="brides-img col-12 col-sm-6 d-flex justify-content-center justify-content-sm-end">
                    <img class="rounded-circle" src="https://res.cloudinary.com/ksjl86/image/upload/v1691584723/janemike_bvwgnx.webp" alt="Image of bride and groom Jane & Mike on their wedding day">
                </div>
            </div>
            <div class="row pt-2">
                <div class="brides-text-first col-12 col-sm-6">
                    <h3>Lizzie & Henry</h3>
                    <p><em>"I was so pleased that I was able to find a truly unique dress that really reflected my personality. Samantha went to such lengths to listen to my long list of must-haves and helped me find the one!"</em></p>
                </div>
                <div class="brides-img col-12 col-sm-6 d-flex justify-content-center justify-content-sm-start">
                    <img class="rounded-circle" src="https://res.cloudinary.com/ksjl86/image/upload/v1693650802/bride2_dp4xja.webp" alt="Image of bride and groom Lizzie & Henry on their wedding day">
                </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

product/templates/product_details.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid body-content">
    <div class="mt-3 pt-3 row card-body">
        <div class="image-container col-sm">
            <img src=" {{ product.main_image.url }}" alt="product image">
        </div>  
        <div class="col-sm">
            <h2 class="pt-2">{{ product.item_name }}</h2>
            <p class="lead pt-2 product-summary">{{ product.description }}</p>
            <div class="info-border p-2 mb-3">
                <div class="row">
                    <p class="col-4">Collection:</p>
                    <p class="col-8">{{ product.category }}</p>
                </div>
                <div class="row">
                    <p class="col-4">Colours:</p>
                    <p class="col-8">{{ product.colours }}</p>
                </div>
                <div class="row">
                    <p class="col-4">Available in sizes:</p>
                    <p class="col-8">{{ product.sizes_avail }}</p>
                </div>
                <div class="row">
                    <p class="col-4">Price:</p>
                    <p class="col-8">£{{ product.price }}</p>
                </div>
            </div>
            {% if user.is_authenticated %}
                <form action="{% url 'customer_fav' product.pk %}" method="POST">
                    {% csrf_token %}

                    {% if liked %}
                        <button type="submit", name="product_id", value="{{ product.id }}", class="btn btn-outline-primary btn-sm">Remove from Favourites</button>
                    {% else %}
                        <button type="submit", name="product_id", value="{{ product.id }}", class="btn btn-outline-danger btn-sm">Add to Favourites</button>
                    {% endif %}
                </form>
            {% else %}
                <p><em><a href="{% url 'login' %}">Login</a> to save this dress to your Favourites</em></p>
            {% endif %}
        </div>
    </div>

</div>

{% endblock %} 